{% set name = "python-constraint2" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_constraint2-{{ version }}.tar.gz
  sha256: 94de42fc08dfb4fcef800d1d974609a25a842983543f96f97440ab2694c8763a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython >=3.0.12
    - pip
    - poetry-core >=2.0.1
    - python
    - setuptools >=75.8.0
  run:
    - python

test:
  commands:
    - pip check
    - pytest --no-cov --ignore tests/test_constraint.py --ignore tests/test_compilation.py
  imports:
    - constraint
  requires:
    - pep440
    - pip
    - pytest
    - pytest-benchmark
    - pytest-cov
    - tomli
  source_files:
    - pyproject.toml
    - tests
    - README.rst

about:
  home: https://github.com/python-constraint/python-constraint
  summary: A module for efficiently solving CSPs (Constraint Solving Problems) over finite domains.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: http://python-constraint.github.io/python-constraint

extra:
  recipe-maintainers:
    - bouweandela
    - fjwillemsen
