{% set name = "python-constraint2" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_constraint2-{{ version }}.tar.gz
  sha256: 4f05dd519e88ce1b6212963f7db032fb35194c466579e293e22ce3f091d65665

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython >=3.0.2
    - pip
    - poetry-core >=1.7.0
    - python
    - setuptools >=67.7.2
  run:
    - python

test:
  commands:
    - pip check
    - pytest --no-cov --ignore tests/test_constraint.py --ignore tests/test_compilation.py
  imports:
    - constraint
  requires:
    - pep440
    - pip
    - pytest
    - pytest-cov
    - tomli
  source_files:
    - pyproject.toml
    - tests
    - README.rst

about:
  home: https://github.com/python-constraint/python-constraint
  summary: A module for efficiently solving CSPs (Constraint Solving Problems) over finite domains.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: http://python-constraint.github.io/python-constraint

extra:
  recipe-maintainers:
    - bouweandela
    - fjwillemsen
