schema_version: 1

context:
  python_min: "3.11"
  version: "2.7.0"

package:
  name: python-constraint2
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-constraint2/python_constraint2-${{ version }}.tar.gz
  sha256: d4e65fc5cfe3d7533bdc679dd922823542109f3d18e0c57ffa16047a445819f1

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip:
    - match(python, "<" ~ python_min)

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - poetry-core
    - setuptools >=75.8.0
    - cython >=3.0.12
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - constraint
      pip_check: true
  - files:
      source:
        - pyproject.toml
        - tests
        - README.rst
    requirements:
      run:
        - pep440
        - pytest
        - pytest-benchmark
        - tomli
    script:
      - pytest --ignore tests/test_constraint.py --ignore tests/test_compilation.py -o addopts=

about:
  summary: python-constraint is a module for efficiently solving CSPs (Constraint Solving Problems) over finite domains.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: http://python-constraint.github.io/python-constraint/
  documentation: http://python-constraint.github.io/python-constraint/

extra:
  recipe-maintainers:
    - bouweandela
    - fjwillemsen
